### ISSUE TITLE
Uniqueness of Hidato puzzles

### ISSUE THREAD

**Issue by mmazzarolo** [dmackinnon1/kixote#1]
Hi there!  
Loving your stuff!   

I know that an issue might not be the best place to ask this, but you seem to be super-prepared on math-related stuff, so... do you have any idea on how to implement a way to build an Hidato board and showing some tiles that ensures an unique solution to the puzzle?  
Any suggestion/hint is super appreciated.  

Thank you in advance, keep up the good work :)

**Comment by dmackinnon1** [comment]
Hi - no problem, this *is* an issue. :)

I've been thinking about this also. The puzzles generated here are definitely not guaranteed to have a unique solution, and some may say this disqualifies them from being considered true (or at least good) puzzles at all. As far as I know, puzzles for publication are tested to ensure that they have a unique solution (published Sudoku puzzles for example, should meet this criteria). I console myself on this point by thinking of the puzzles generated here more as games or less formal puzzles. 

In the puzzles here, we can guarantee the existence of a solution - this is from the way the puzzles are generated (the fact that we start from a solution and then cover up some squares). 

To guarantee uniqueness is more time consuming. I think we would have to essentially search through the tree of possible solution attempts and eliminate them. One way to do this would be to implement a solver algorithm that will go through all options at each juncture and backtrack to your last choice when a problem or solution is hit.

**Comment by mmazzarolo** [comment]
> To guarantee uniqueness is more time consuming. I think we would have to essentially search through the tree of possible solution attempts and eliminate them. One way to do this would be to implement a solver algorithm that will go through all options at each juncture and backtrack to your last choice when a problem or solution is hit.  

That's the first solution that came to my mind too: 
1. Choose a certain set of tiles to show (1/4 of the total number of tiles for example);
2. "Fix" the multiple paths using a solver algorithm. 

It seems logic, but at the same time it makes me wonder what kind of solutions do the other puzzle generators use.    

Anyway, thank you for the quick and detailed answer.  
I'm closing the issue but I'll make sure to come back if I discover anything else interesting on the subject :)

**Comment by dmackinnon1** [comment]
Thanks Matteo - I would appreciate any further thoughts you have on this. 

Naively, I was considering having the solver start at the beginning of the puzzle and working its way through. The solver maintains a list of cells that it has moved to. Wherever there is a choice associated with a step, the solver retains a list of alternate choices. When a problem/solution is hit, an alternate choice is tried for the last node. When all choices for that last node are exhausted, it is popped from the solution (its options are reset), and now the next option of the now-top node is chosen. This is a sort of classic brute-force with backtracking approach, I think.

Thanks again

**Comment by dmackinnon1** [comment]
I have updated the code so that uniqueness can be enforced.

**Comment by mmazzarolo** [comment]
Thank you so much, I replied you by mail.
